modLoader = "javafml"
loaderVersion = "[1,)"
license="GPL-3.0"
showAsResourcePack=false

[[mixins]]
config="fgui.mixins.json"

[[mods]]
modId="fgui"
version="${mod_version}"
displayName="fgui"
logoFile="assets/icon.png"
authors="Clickism"
description='''
Library for creating server side guis!
'''

[[dependencies.fgui]]
modId="neoforge"
type="required"
versionRange="*"
side="BOTH"

[[dependencies.fgui]]
modId = "minecraft"
type = "required"
versionRange = "*"
side = "BOTH"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"